//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rvFleet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class archivofactura
    {
        public int FacArchivoCodigo { get; set; }
        public int FacCodigoOrden { get; set; }
        public Nullable<System.DateTime> FacArchivoFechaSubida { get; set; }
        public string FacArchivoUsuario { get; set; }
        public string FacArchivoUrl { get; set; }
        public string FacArchivoNombre { get; set; }
    
        public virtual facturas facturas { get; set; }
    }
}
