//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rvFleet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class archivofactura
    {
        public int FacArchivoCodigo { get; set; }
        public int FacCodigoOrden { get; set; }
        public Nullable<System.DateTime> FacArchivoFechaSubida { get; set; }
        public string FacArchivoUsuario { get; set; }
        public string FacArchivoUrl { get; set; }
        public string FacArchivoNombre { get; set; }
    
        public virtual facturas facturas { get; set; }
    }
}
