//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rvFleet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bitacoracomentario
    {
        public int bitacoraId { get; set; }
        public int bitacoraComId { get; set; }
        public string bitacoraComRespuesta { get; set; }
        public string bitacoraComUsuario { get; set; }
        public Nullable<System.DateTime> bitacoraComFecha { get; set; }
    
        public virtual bitacoravehiculo bitacoravehiculo { get; set; }
    }
}
