//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rvFleet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bitacoravehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bitacoravehiculo()
        {
            this.bitacoracomentario1 = new HashSet<bitacoracomentario>();
        }
    
        public int bitacoraId { get; set; }
        public string bitacoraComentario { get; set; }
        public string bitacoraUsuario { get; set; }
        public Nullable<System.DateTime> bitacoraFecha { get; set; }
        public string bitacoraPlaca { get; set; }
        public string bitacoraTipo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bitacoracomentario> bitacoracomentario1 { get; set; }
    }
}
