//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rvFleet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class conductorhistorico
    {
        public string ConPlaca { get; set; }
        public int ConCodigoCarro { get; set; }
        public System.DateTime ConFechaAsignado { get; set; }
        public int ConKilometrajeAsignacion { get; set; }
        public int ConCodigoConductor { get; set; }
    }
}
