//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rvFleet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class conductorhistorico
    {
        public string ConPlaca { get; set; }
        public int ConCodigoCarro { get; set; }
        public System.DateTime ConFechaAsignado { get; set; }
        public int ConKilometrajeAsignacion { get; set; }
        public int ConCodigoConductor { get; set; }
    }
}
