//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rvFleet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class controlvehiculosrespuestadetalle
    {
        public int IdControl { get; set; }
        public int CodigoVehiculo { get; set; }
        public int Kilometraje { get; set; }
        public string Observacion { get; set; }
    }
}
