//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rvFleet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class controlvehiculospregunta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public controlvehiculospregunta()
        {
            this.controlvehiculosrespuesta = new HashSet<controlvehiculosrespuesta>();
        }
    
        public int Id { get; set; }
        public string Tipo { get; set; }
        public string Pregunta { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<bool> Requerido { get; set; }
        public Nullable<int> Orden { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<controlvehiculosrespuesta> controlvehiculosrespuesta { get; set; }
    }
}
