//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rvFleet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class controlvehiculosrespuesta
    {
        public int Id { get; set; }
        public int CodigoVehiculo { get; set; }
        public int CodigoPregunta { get; set; }
        public System.DateTime Fecha { get; set; }
        public string CodigoUsuario { get; set; }
        public string Respuesta { get; set; }
        public string Observacion { get; set; }
    
        public virtual controlvehiculospregunta controlvehiculospregunta { get; set; }
    }
}
