//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rvFleet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detallefactura
    {
        public int DetCodigoDetalle { get; set; }
        public int DetCodigoOrden { get; set; }
        public string DetDescripcion { get; set; }
        public double DetValor { get; set; }
        public int DetCantidad { get; set; }
        public string DetPlacaVehiculo { get; set; }
        public Nullable<int> DetCodigoRubro { get; set; }
        public int DetKilometraje { get; set; }
    
        public virtual facturas facturas { get; set; }
    }
}
