//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rvFleet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detallefactura
    {
        public int DetCodigoDetalle { get; set; }
        public int DetCodigoOrden { get; set; }
        public string DetDescripcion { get; set; }
        public double DetValor { get; set; }
        public int DetCantidad { get; set; }
        public string DetPlacaVehiculo { get; set; }
        public string DetCodigoRubro { get; set; }
    
        public virtual facturas facturas { get; set; }
    }
}
