//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rvFleet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class facturas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public facturas()
        {
            this.detallefactura = new HashSet<detallefactura>();
        }
    
        public int FacCodigoOrden { get; set; }
        public Nullable<System.DateTime> FacFechaFactura { get; set; }
        public int FacCodigoProveedor { get; set; }
        public string FacNumeroFactura { get; set; }
        public int FacCodigoDetalleFactura { get; set; }
        public double FacValorFactura { get; set; }
        public string FacComentario { get; set; }
        public Nullable<System.DateTime> FacFechaEntregaAdmin { get; set; }
        public string FacUrlFoto { get; set; }
        public bool FacPagado { get; set; }
        public string FacCodigoUsuarioIngreso { get; set; }
        public Nullable<System.DateTime> FacFechaOrden { get; set; }
        public string FacKilometraje { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detallefactura> detallefactura { get; set; }
        public virtual proveedor proveedor { get; set; }
    }
}
