//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rvFleet.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class rvfleetEntities : DbContext
    {
        public rvfleetEntities()
            : base("name=rvfleetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<conductorhistorico> conductorhistorico { get; set; }
        public virtual DbSet<detallefactura> detallefactura { get; set; }
        public virtual DbSet<facturas> facturas { get; set; }
        public virtual DbSet<kilometrajehistorico> kilometrajehistorico { get; set; }
        public virtual DbSet<proveedor> proveedor { get; set; }
        public virtual DbSet<rubrodetalle> rubrodetalle { get; set; }
        public virtual DbSet<rubros> rubros { get; set; }
        public virtual DbSet<sucursales> sucursales { get; set; }
        public virtual DbSet<ubicacionhistorica> ubicacionhistorica { get; set; }
        public virtual DbSet<vehiculos> vehiculos { get; set; }
    }
}
