//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rvFleet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kilometrajeporvehiculoanoactual
    {
        public int KilCodigoVehiculo { get; set; }
        public System.DateTime KilFechaIngreso { get; set; }
        public Nullable<int> KilFechaIngreso_Mes { get; set; }
        public Nullable<int> KilKilometraje { get; set; }
        public string VehPlaca { get; set; }
        public string VehColorIdentificador { get; set; }
    }
}
