//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rvFleet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class opcionrecurso
    {
        public string IdGrupoRecurso { get; set; }
        public string IdOpcionRecurso { get; set; }
        public string NombreOpcionRecurso { get; set; }
        public string DescripcionOpcionRecurso { get; set; }
        public Nullable<bool> Estatus { get; set; }
    
        public virtual gruporecurso gruporecurso { get; set; }
    }
}
