//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rvFleet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class opcionrecurso
    {
        public string IdGrupoRecurso { get; set; }
        public string IdOpcionRecurso { get; set; }
        public string NombreOpcionRecurso { get; set; }
        public string DescripcionOpcionRecurso { get; set; }
        public Nullable<bool> Estatus { get; set; }
    
        public virtual gruporecurso gruporecurso { get; set; }
    }
}
