//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rvFleet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class privilegio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public privilegio()
        {
            this.rol = new HashSet<rol>();
        }
    
        public string IdPrivilegio { get; set; }
        public string NombrePrivilegio { get; set; }
        public bool EstadoPrivilegio { get; set; }
        public Nullable<int> NivelPrivilegio { get; set; }
        public string PadrePrivilegio { get; set; }
        public string DescripcionPrivilegio { get; set; }
        public string URL { get; set; }
        public string Parametros { get; set; }
        public string Icono { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rol> rol { get; set; }
        public virtual privilegiopermiso privilegiopermiso { get; set; }
    }
}
