//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rvFleet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class recommendedmaintenance
    {
        public int CodigoRubro { get; set; }
        public string NombreRubro { get; set; }
        public string DetPlacaVehiculo { get; set; }
        public int VehCodigoVehiculo { get; set; }
        public Nullable<int> DistanciaCambio { get; set; }
        public Nullable<int> KilometrajeFacturado { get; set; }
        public Nullable<int> KilometrajeActual { get; set; }
        public Nullable<long> DistanciaRecorrida { get; set; }
        public Nullable<long> VidaRestante { get; set; }
        public int DetCodigoOrden { get; set; }
        public Nullable<System.DateTime> FacFechaOrden { get; set; }
        public Nullable<int> Prioridad { get; set; }
    }
}
