//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rvFleet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rubrodetalle
    {
        public int CodigoRubro { get; set; }
        public int CodigoDetalle { get; set; }
        public string NombreDetalle { get; set; }
    
        public virtual rubros rubros { get; set; }
    }
}
