//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rvFleet.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class rvseguridadEntities1 : DbContext
    {
        public rvseguridadEntities1()
            : base("name=rvseguridadEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<departamento> departamento { get; set; }
        public virtual DbSet<empresa> empresa { get; set; }
        public virtual DbSet<gruporecurso> gruporecurso { get; set; }
        public virtual DbSet<opcionrecurso> opcionrecurso { get; set; }
        public virtual DbSet<posicion> posicion { get; set; }
        public virtual DbSet<privilegio> privilegio { get; set; }
        public virtual DbSet<privilegiopermiso> privilegiopermiso { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<ubicacion> ubicacion { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
