//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rvFleet.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class rvseguridadEntities1 : DbContext
    {
        public rvseguridadEntities1()
            : base("name=rvseguridadEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<empresa> empresa { get; set; }
        public virtual DbSet<posicion> posicion { get; set; }
        public virtual DbSet<privilegio> privilegio { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<departamento> departamento { get; set; }
        public virtual DbSet<gruporecurso> gruporecurso { get; set; }
        public virtual DbSet<opcionrecurso> opcionrecurso { get; set; }
        public virtual DbSet<ubicacion> ubicacion { get; set; }
        public virtual DbSet<privilegiopermiso> privilegiopermiso { get; set; }
        public virtual DbSet<usuariodepartamentoposicion> usuariodepartamentoposicion { get; set; }
    }
}
