//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rvFleet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ubicacionhistorica
    {
        public int UbiCodigoAuto { get; set; }
        public string UbiPlaca { get; set; }
        public int UbiCodigoSucursal { get; set; }
        public System.DateTime UbiFechaCambio { get; set; }
    }
}
