//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rvFleet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ubicacionhistorica
    {
        public int UbiCodigoAuto { get; set; }
        public string UbiPlaca { get; set; }
        public int UbiCodigoSucursal { get; set; }
        public System.DateTime UbiFechaCambio { get; set; }
    }
}
