//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rvFleet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuariodepartamentoposicion
    {
        public string IdUsuario { get; set; }
        public int IdDepartamento { get; set; }
        public int IdPosicion { get; set; }
    
        public virtual departamento departamento { get; set; }
        public virtual posicion posicion { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
