//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rvFleet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public int CodigoRRHH { get; set; }
        public string IdUsuario { get; set; }
        public string Contrasena { get; set; }
        public string Estado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string NombreUsuario { get; set; }
        public int IdUbicacion { get; set; }
        public string Jefe { get; set; }
        public string Correo { get; set; }
        public string IdentidadUsuario { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public string IdEmpresa { get; set; }
    }
}
