//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rvFleet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuario()
        {
            this.rol = new HashSet<rol>();
            this.usuariodepartamentoposicion = new HashSet<usuariodepartamentoposicion>();
        }
    
        public int CodigoRRHH { get; set; }
        public string IdUsuario { get; set; }
        public string Contrasena { get; set; }
        public string Estado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string NombreUsuario { get; set; }
        public int IdUbicacion { get; set; }
        public string Jefe { get; set; }
        public string Correo { get; set; }
        public string IdentidadUsuario { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public string IdEmpresa { get; set; }
    
        public virtual empresa empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rol> rol { get; set; }
        public virtual ubicacion ubicacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuariodepartamentoposicion> usuariodepartamentoposicion { get; set; }
    }
}
