//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rvFleet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuario()
        {
            this.rol = new HashSet<rol>();
        }
    
        public string CodigoRRHH { get; set; }
        public string IdUsuario { get; set; }
        public string Contrasena { get; set; }
        public string Estado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string NombreUsuario { get; set; }
        public int IdUbicacion { get; set; }
        public string Jefe { get; set; }
        public string Correo { get; set; }
        public string IdentidadUsuario { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public string IdEmpresa { get; set; }
    
        public virtual empresa empresa { get; set; }
        public virtual ubicacion ubicacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rol> rol { get; set; }
    }
}
