//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rvFleet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehiculos
    {
        public int VehCodigoVehiculo { get; set; }
        public string VehPlaca { get; set; }
        public string VehVIN { get; set; }
        public string VehMotor { get; set; }
        public string VehCilindraje { get; set; }
        public int VehAno { get; set; }
        public string VehColor { get; set; }
        public string VehMarca { get; set; }
        public string VehModelo { get; set; }
        public string VehCodigoAresSun { get; set; }
        public Nullable<int> VehCodigoProveedor { get; set; }
        public string VehCodigoEmpresa { get; set; }
        public System.DateTime VehFechaMatricula { get; set; }
        public string VehNumeroPoliza { get; set; }
        public string VehUrlFotoRevision { get; set; }
        public string VehCodigoUsuario { get; set; }
        public string VehFotoFrontal { get; set; }
        public string VehFotoLateralDerecha { get; set; }
        public string VehFotoLateralIzquierda { get; set; }
        public string VehFotoTrasera { get; set; }
        public string VehFotoMotor { get; set; }
        public string VehFotoInterior { get; set; }
        public Nullable<int> VehKilometraje { get; set; }
        public string VehColorIdentificador { get; set; }
    
        public virtual proveedor proveedor { get; set; }
    }
}
